default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: muffin_base
  password: 121212

development:
  <<: *default
  database:  muffin_app_development

production:
  <<: *default
  database: muffin_app_production

test:
  <<: *default
  database: muffin_app_test